### ISSUE TITLE
CSV/KML Export options not functioning

### ISSUE THREAD

**Issue by JGoldmanRicondo** [jpatokal/openflights#1063]
CSV and KML export options have not been working for us the past few days. Is there a workaround or a browser setting we possibly have hindering our export?

Thank you

**Comment by sww326** [comment]
Same issue, but I've been experiencing it for more than a week now. I have tested on both Chrome and Edge browsers, and on multiple machines.

**Comment by JGoldmanRicondo** [comment]
Still no luck on our end :(

**Comment by JGoldmanRicondo** [comment]
Issue Resolved: Fixed by using Firefox instead of Chrome.

**Comment by sww326** [comment]
Weird! I tried Chrome, Edge and Opera without luck. Sure enough, Firefox works for some reason. Thanks.

**Comment by devmind-ua** [comment]
Haven't dig this issue but calling [https://openflights.org/php/flights.php?user=0&trid=0&alid=0&year=0&param=MAP&id=0&export=export](https://openflights.org/php/flights.php?user=0&trid=0&alid=0&year=0&param=MAP&id=0&export=export) does the job for me in Chrome.

**Comment by jpatokal** [comment]
Traced this to Chrome now blocking invocations of HTTP URLs from HTTPS sites (like OpenFlights).  Updated download links to use HTTPS, so this should be fixed now.

**Comment by iceman85** [comment]
Hello Jani,

Export function tested out in Chrome 97.0.4692.99 with both .csv and .kml
extensions. It works like a charm!

Truly hope it will be possible to fix the Country list that is still read
as ALL without further options, thus no more data can be imported in the
system when creating an airport.


Last but not the least... please have a look at Issue #677 . I created the
airport in 2017, but I misread the coordinates. New coordinates have been
provided already, in pending since November 2017.


Keep up the great job!!

Cheers,
Stefano
