### ISSUE TITLE
PHP Notice: Undefined index: fid in flights.php on line 29

### ISSUE THREAD

**Issue by reedy** [jpatokal/openflights#1155]
```
  $fid = $_POST["fid"];
```

What should it default to?

**Comment by chrisrosset** [comment]
I looked a bit at this yesterday because I was hoping to eliminate PHP 7 warnings before looking at PHP 8 compatibility.

My understanding is that this code (all the reads out of `$_POST` and `$_GET`) were written assuming that reading an undefined returns `null`. For `fid`, I think this is corroborated by checks like `if ($fid && $fid != "0")` and `(!$fid || $fid == "0")`.

Is it a good idea to add `?? null` to all of them? Maybe it'd be better to declare all of the variables up top and assign the `null` default and then only re-assign if the value is present?

Or maybe we should just switch on the method (we seem to only have `GET` and `POST`) and just declare/assign all of them?

```php
switch($_SERVER['REQUEST_METHOD']) {
    case "POST":
        $apid = $_POST["id"] ?? null;
        $trid = $_POST["trid"] ?? null;
        $alid = $_POST["alid"] ?? null;
        $fid = $_POST["fid"] ?? null;
        $user = $_POST["user"] ?? null;
        $year = $_POST["year"] ?? null;
        break;
    case "GET":
        $apid = $_GET["id"] ?? null;
        $trid = $_GET["trid"] ?? null;
        $alid = $_GET["alid"] ?? null;
        $fid = $_GET["fid"] ?? null;
        $user = $_GET["user"] ?? null;
        $year = $_GET["year"] ?? null;
        break;
    default:
        die("Unsupported method");
}
```

**Comment by reedy** [comment]
It's not worth declaring variables that aren't used; it just adds to confusion that you don't know if it's supposed to be used (and isn't) etc.

Most can probably be defaulted to null, when read though. This does seem to be common for the POST/GET variables, but not so consistent for other variables, for example like seen in https://github.com/jpatokal/openflights/pull/1152

**Comment by chrisrosset** [comment]
> Most can probably be defaulted to null, when read though. This does seem to be common for the POST/GET variables, but not so consistent for other variables, for example like seen in #1152

Wouldn't this one also work `null` as the default?

**Comment by reedy** [comment]
> > Most can probably be defaulted to null, when read though. This does seem to be common for the POST/GET variables, but not so consistent for other variables, for example like seen in #1152
> 
> Wouldn't this one also work `null` as the default?

Well, it would... But it's being used as a bool, so you define/default it as a bool

https://github.com/jpatokal/openflights/blame/master/php/flights.php#L70
https://github.com/jpatokal/openflights/blame/master/php/flights.php#L113-L115

PHP's idea that everything can be implicitly evaluated to something true-y/false-y is a blessing and a curse.

**Comment by chrisrosset** [comment]
> Well, it would... But it's being used as a bool, so you define/default it as a bool

No argument there.

I think adding `?? null` makes sense for reads that produce warnings and we could keep the others as they are. I can send a PR for the warnings I can see (including this and #1154).

**Comment by reedy** [comment]
Feel free :)
