### ISSUE TITLE
openflights.js: Inconsistent indenting

### ISSUE THREAD

**Issue by reedy** [jpatokal/openflights#1235]
Tabs, spaces... Not actually aligned...

**Comment by chrisrosset** [comment]
What do you think about doing using something like `prettier` to auto-format all the JavaScript? We could also set up a PR hook to check formatting.

**Comment by reedy** [comment]
Some sort of automation would be good.

I've not really touched any of the JS to this extent, but something we can wire into CI would definitely be the way forward.

There's numerous tools/libraries for enforcing JS (and CSS etc) et al coding standards.

Somewhere down the line we probably want to look at minification of the JS etc for performance in deployments.

Not that the repo has that much JS... it's all gonna help :)

**Comment by chrisrosset** [comment]
Linking a related formatting discussion: https://github.com/jpatokal/openflights/pull/1223#issuecomment-1627829530

**Comment by reedy** [comment]
> What do you think about doing using something like `prettier` to auto-format all the JavaScript?

I don't personally have any strong opinions either way...

https://eslint.org/ would be another option, as it does some amount of static analysis too

**Comment by chrisrosset** [comment]
ESLint is not recommended for formatting these days. Best to keep formatting and linting separate.

Enabling ESLint would be useful but I would recommend silencing all the warnings at first and then enabling them one by one. There's going to be a lot of warnings. :)

I'll leave the formatting decisions to you since you've already started the work and you also have the privs to enable checks on PRs.
