### ISSUE TITLE
Notes field does not clear when you navigate with < > in flight editor mode

### ISSUE THREAD

**Issue by reevery** [jpatokal/openflights#1452]
Hi. I was editing some flights today using the GUI. I noticed that when you start with a flight with notes, then navigate to the previous or next using the navigation buttons < or >, the notes field does not clear. That means, if you save the next flight, you save the notes from the previous flight to every other until you notice.

**Comment by reedy** [comment]
It's not just `<`/`>`; if you click edit on one, exit, and then edit on another that doesn't have a note set... that note will also load...

**Comment by reedy** [comment]
I suspect the issue is related to this:

```js
  if(col[16] != "") {
    $('note').style.color = '#000';
    form.note.value = col[16];
  } else {
    $('note').value = $('note').hintText;
  }
```

The `else` case was removed when doing some refactoring of the hinted text boxes. In the old version, if the column from the DB was not `""`, we set the text, falling back to the hint text. This isn't needed now, so we don't clear the state properly... Easily fixed at least.
