### ISSUE TITLE
Gett current airports.dat file

### ISSUE THREAD

**Issue by bmomjian** [jpatokal/openflights#593]
Is there any way to get a more current copy of airports.dat, as it is over two years old now.  As I understand it, airports.dat is just a snapshot copy of what is on the website.  I assume there is no easy way to get a current copy of the airport database.

**Comment by hhsprings** [comment]
I need also up-dated database in order to list locations (ARP) of aerodromes.

I'd investigated aerodromes that airports.dat doesn't have but exist in wikipedia with my simple script. Please see [ICAO_codes_not_in_openflights_but_in_wikipedia_with_location.csv](https://drive.google.com/open?id=0BxeC8fgTf_eGSnRrdTdoSm1wRmc) ~~[ICAO_codes_not_in_openflights_but_in_wikipedia_with_location.csv](https://drive.google.com/open?id=0BxeC8fgTf_eGRzEtX3Y0QS1MMk0)~~ ~~[ICAO_codes_not_in_openflights_but_in_wikipedia.csv](https://drive.google.com/open?id=0BxeC8fgTf_eGZkdtUzd2Tk1tQ28)~~.

I don't think all of these are needed, but at least i want [stations reporting METAR](http://tgftp.nws.noaa.gov/data/observations/metar/stations).

**Comment by bmomjian** [comment]
The download file is now more current, so this item can be closed.

**Comment by bmomjian** [comment]
Can we get an updated airports.dat file?  It is missing the BER/Berlin airport.  The ISB airport also needs a time zone, and DOH is missing.  Thanks.
